export const typeIcons: Record<string, string> = {
  bug: '/icons/type/bug.svg',
  dark: '/icons/type/dark.svg',
  dragon: '/icons/type/dragon.svg',
  electric: '/icons/type/electric.svg',
  fairy: '/icons/type/fairy.svg',
  fighting: '/icons/type/fighting.svg',
  fire: '/icons/type/fire.svg',
  flying: '/icons/type/flying.svg',
  ghost: '/icons/type/ghost.svg',
  grass: '/icons/type/grass.svg',
  ground: '/icons/type/ground.svg',
  ice: '/icons/type/ice.svg',
  normal: '/icons/type/normal.svg',
  poison: '/icons/type/poison.svg',
  psychic: '/icons/type/psychic.svg',
  rock: '/icons/type/rock.svg',
  steel: '/icons/type/steel.svg',
  water: '/icons/type/water.svg',
}
